WebBanHang/Areas/Customer/Models/Cart.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebBanHang.Models;

namespace WebBanHang.Areas.Customer.Models
{
    //lớp biểu diễn 1 phần tử của giỏ hàng
    public class CartItem
    {

        public Product Product { get; set; }
        public int Quantity { get; set; }
    }

    // lớp biểu diễn giỏ hàng
    public class Cart
    {
        private List<CartItem> _items;
        public Cart()
        {
            _items = new List<CartItem>();
        }
        public List<CartItem> Items { get { return _items; } }

        //thêm sản phẩm vào giỏ
        public void Add(Product p, int qty)
        {
            var item = _items.FirstOrDefault(x => x.Product.Id == p.Id);
            if (item == null) //chưa có
            {
                _items.Add(new CartItem { Product = p, Quantity = qty });
            }
            else
            {
                item.Quantity += qty;
            }
        }

        //cập nhật số lượng
        public void Update(int productId, int qty)
        {
            var item = _items.FirstOrDefault(x => x.Product.Id == productId);
            if (item != null)//tồn tại
            {
                if (qty > 0)
                {
                    item.Quantity = qty;
                }
                else
                {
                    _items.Remove(item);
                }
            }
        }

        //xóa sản phẩm khỏi giỏ hàng
        public void Remove(int productId)
        {
            var item = _items.FirstOrDefault(x => x.Product.Id == productId);
            if (item != null)
            {
                _items.Remove(item);
            }
        }

        //tính tổng thành tiền sản phẩm
        public double Total
        {
            get
            {
                double total = _items.Sum(x => x.Quantity * x.Product.Price);

                return total;
            }
        }

        //tính tổng số lượng sản phẩm
        public double Quantity
        {
            get
            {
                double total = _items.Sum(x => x.Quantity);
                return total;
            }
        }
    }
}

WebBanHang/Areas/Customer/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebBanHang.Areas.Customer.Models;
using WebBanHang.Models;

namespace WebBanHang.Areas.Customer.Controllers
{
    [Area("Customer")]
    public class CartController : Controller
    {
        private readonly ApplicationDbContext _db;
        public CartController(ApplicationDbContext db)
        {
            _db = db;
        }

        //hiển thị giao diện quản lý giỏ hàng
        public IActionResult Index()
        {
            Cart cart = HttpContext.Session.GetJson<Cart>("CART");
            if (cart == null)
            {
                cart = new Cart();
            }
            return View(cart);
        }

        //xử lý thêm sản phẩm vào giỏ hàng
        public IActionResult AddToCart(int productId)
        {
            var product = _db.Products.FirstOrDefault(x => x.Id == productId);
            if (product != null)
            {
                Cart cart = HttpContext.Session.GetJson<Cart>("CART");
                if (cart == null)
                {
                    cart = new Cart();
                }
                cart.Add(product, 1);
                HttpContext.Session.SetJson("CART", cart);
                // return Json(new { msg="success", qty = cart.Quantity});
                return RedirectToAction("Index");
            }
            return Json(new { msg = "error" });
        }

        //xử lý cập nhật số lượng
        public IActionResult Update(int productId, int qty)
        {
            var product = _db.Products.FirstOrDefault(x => x.Id == productId);
            if (product != null)
            {
                //lấy cart từ Session
                Cart cart = HttpContext.Session.GetJson<Cart>("CART");
                if (cart != null)
                {
                    cart.Update(productId, qty); //cập nhật lại số lượng
                    HttpContext.Session.SetJson("CART", cart); //lưu cart vào Session
                    return RedirectToAction("Index");
                }
            }

            return Json(new { msg = "error" });
        }

        //xử lý xoá sản phẩm trong giỏ hàng
        public IActionResult Remove(int productId)
        {
            var product = _db.Products.FirstOrDefault(x => x.Id == productId);
            if (product != null)
            {
                //lấy cart từ Session
                Cart cart = HttpContext.Session.GetJson<Cart>("CART");
                if (cart != null)
                {
                    cart.Remove(productId); //xoá sản phẩm khỏi giỏ
                    HttpContext.Session.SetJson("CART", cart); //lưu cart vào Session
                    return RedirectToAction("Index");
                }
            }
            return NotFound();
        }

        //ajax
        public IActionResult AddToCartAPI(int productId)
        {
            var product = _db.Products.FirstOrDefault(x => x.Id == productId);
            if (product != null)
            {
                Cart cart = HttpContext.Session.GetJson<Cart>("CART");
                if (cart == null)
                {
                    cart = new Cart();
                }
                cart.Add(product, 1);
                HttpContext.Session.SetJson("CART", cart);
                return Json(new { msg = "Product added to cart", qty = cart.Quantity });
            }
            return Json(new { msg = "error" });
        }
        public IActionResult GetQuantityOfCart()
        {
            Cart cart = HttpContext.Session.GetJson<Cart>("CART");
            if (cart != null)
            {

                return Json(new { qty = cart.Quantity });
            }
            return Json(new { qty = 0 });
        }
    }
}

WebBanHang/Areas/Customer/Controllers/OrderController.cs
using System;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WebBanHang.Areas.Customer.Models;
using WebBanHang.Models;

namespace WebBanHang.Areas.Customer.Controllers
{
    [Area("Customer")]
    [Authorize]
    public class OrderController : Controller
    {
        private readonly ApplicationDbContext _db;
        public OrderController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            //lấy cart từ Session
            Cart cart = HttpContext.Session.GetJson<Cart>("CART");
            if (cart == null)
            {
                cart = new Cart();
            }
            //gửi cart qua View thông qua ViewBag
            ViewBag.CART = cart;
            return View();
        }
        public IActionResult ProcessOrder(Order order)
        {
            Cart cart = HttpContext.Session.GetJson<Cart>("CART");
            if (ModelState.IsValid)
            {
                //Lưu trữ đơn hàng
                //b1 Thêm Order vào CSDL

                //tạo đơn hàng
                order.OrderDate = DateTime.Now;
                order.Total = cart.Total;
                order.State = "Pending";
                //thêm Order vào CSDL
                _db.Orders.Add(order);
                _db.SaveChanges();
                //b2 Thêm OrderDetail vào CSDL
                foreach (var item in cart.Items) //duyệt qua từng sản phẩm trong giỏ hàng
                {
                    //tạo đối tượng OrderDetail
                    var orderDetail = new OrderDetail
                    {

                        OrderId = order.Id,
                        ProductId = item.Product.Id,
                        Quantity = item.Quantity
                    };
                    //them OrderDetail vào CSDL
                    _db.OrderDetails.Add(orderDetail);
                    _db.SaveChanges();

                }
                //b3 xóa giỏ hàng
                HttpContext.Session.Remove("CART");
                //b4 trả về View kết quả
                return View("Result");
            }
            //gửi cart qua View thông qua ViewBag
            ViewBag.CART = cart;
            return View("Index", order);
        }
    }
}

WebBanHang/Areas/Customer/Views/Cart/Index.cshtml
@model Cart
<section class="bg-light my-5">
    <div class="container">
        <div class="row">
            <!-- cart -->
            <div class="col-lg-9">
                <div class="card border shadow-0">
                    <div class="m-4">
                        <h4 class="card-title mb-4">Your shopping cart</h4>
                        @foreach (var item in Model.Items)
                        {
                            <form asp-action="Update" method="post">
                                <input type="hidden" name="productId" value="@item.Product.Id" />
                                <div class="row gy-3 mb-4">
                                    <div class="col-lg-5">
                                        <div class="me-lg-5">
                                            <div class="d-flex">
                                                <img src="/@item.Product.ImageUrl" class="border rounded me-3" style="width: 96px; height: 96px;" />
                                                <div class="">
                                                    <a href="#" class="nav-link">@item.Product.Name</a>
                                                </div>

                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-lg-2 col-sm-6 col-6 d-flex flex-row flex-lg-column flex-xl-row text-nowrap">
                                        <div class="">
                                            <input type="number" name="qty" value="@item.Quantity" class="form-control" min="1" />
                                        </div>
                                        <div class="">
                                            <text class="h6">@string.Format("${0:#,##0}", item.Product.Price)</text> <br />
                                        </div>
                                    </div>

                                    <div class="col-lg col-sm-6 d-flex justify-content-sm-center justify-content-md-start justify-content-lg-center justify-content-xl-end mb-2">

                                        <div class="float-md-end">
                                            <button type="submit" class="btn btn-light border text-primary icon-hover-primary">
                                                Update
                                            </button>

                                            <a asp-action="Remove" asp-controller="Cart" asp-route-productId="@item.Product.Id" class="btn btn-light border text-danger icon-hover-danger"> Remove</a>

                                        </div>
                                    </div>
                                </div>
                            </form>
                        }
                    </div>
                </div>
            </div>
            <!-- cart -->
            <!-- summary -->
            <div class="col-lg-3">
                <div class="card shadow-0 border">
                    <div class="card-body">
                        <div class="d-flex justify-content-between">
                            <p class="mb-2">Total price:</p>
                            <p class="mb-2">@string.Format("${0:#,##0}", Model.Total)</p>
                        </div>
                        <div class="d-flex justify-content-between">
                            <p class="mb-2">Discount:</p>
                            <p class="mb-2 text-success">-$0</p>
                        </div>
                        <div class="d-flex justify-content-between">
                            <p class="mb-2">TAX:</p>
                            <p class="mb-2">$0.00</p>
                        </div>
                        <hr />
                        <div class="d-flex justify-content-between">
                            <p class="mb-2">Total price:</p>
                            <p class="mb-2 fw-bold">@string.Format("${0:#,##0}", Model.Total)</p>
                        </div>
                        <div class="mt-3">
                            <a asp-action="ProcessOrder" asp-controller="Order" class="btn btn-success w-100 shadow-0 mb-2"> Make Purchase </a>
                            <a href="/customer" class="btn btn-light w-100 border mt-2"> Back to shop </a>
                        </div>
                    </div>
                </div>
            </div>
            <!-- summary -->
        </div>
    </div>
</section>